### ISSUE TITLE
Why is url deprecated?

### ISSUE THREAD

**Issue by gurgunday** [ajv-validator/ajv-formats#101]
Hey!

I couldn't find an explanation as to why [url format is deprecated](https://github.com/ajv-validator/ajv-formats?tab=readme-ov-file#formats)

Will it be completely removed in the future?

**Comment by tschmidtb51** [comment]
I found this: https://github.com/ajv-validator/ajv/issues/898

**Comment by gurgunday** [comment]
Thanks!
