### ISSUE TITLE
Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by leoglobant** [ajv-validator/ajv-formats#12]
I'm using @middy/validator for which I add the plugin with an empty object `{}`. 
Unfortunately I get an error: `TypeError: Cannot read property 'code' of undefined`
Pointing to line https://github.com/ajv-validator/ajv-formats/blob/master/src/index.ts#L55
Please help!

**Comment by mfolkeseth** [comment]
I had the same issue. Try apply formats to the instance:

```js
const Ajv = require('ajv').default;
const AjvFormats = require('ajv-formats');
const ajv = new Ajv();
AjvFormats(ajv);
const validateSchema = ajv.compile(schema);
```

**Comment by cywalker** [comment]
I am having the same issue, throws error on last line. 
addFormats uses ajv.opts.code but ajv object does not have .opts or .opts.code (it does have ._opts but not ._opts.code)
```
import Ajv from 'ajv'; //'../node_modules/ajv/lib/ajv.js'; v7.0.4
import addFormats from 'ajv-formats'; //"../node_modules/ajv-formats/dist/index.js"; v1.5.1
const ajv = new Ajv({
  $data: true,
  allErrors: true,
});
console.log(ajv);
addFormats(ajv);
```
error => Cannot read property 'code' of undefined
errors at node_modules/ajv-formats/dist/index.js:30:1;
```
  28 |     var _a;
  29 |     var _b;
> 30 |     (_a = (_b = ajv.opts.code).formats) !== null && _a !== void 0 ? _a : (_b.formats = codegen_1._ `require("ajv-formats/dist/formats").${exportName}`);
     | ^
  31 |     for (const f of list)
  32 |         ajv.addFormat(f, fs[f]);
  33 | }
```
ajv object;
```
Ajv {_opts: {…}, logger: console, _schemas: {…}, _refs: {…}, _fragments: {…}, …}
RULES: (5) [{…}, {…}, {…}, {…}, {…}, all: {…}, types: {…}, keywords: {…}, custom: {…}]
logger: console {debug: ƒ, error: ƒ, info: ƒ, log: ƒ, warn: ƒ, …}
_cache: Cache {_cache: {…}}
_compilations: []
_formats: {date: /^\d\d\d\d-[0-1]\d-[0-3]\d$/, time: /^(?:[0-2]\d:[0-5]\d:[0-5]\d|23:59:60)(?:\.\d+)?(?:z|[+-]\d\d(?::?\d\d)?)?$/i, date-time: /^\d\d\d\d-[0-1]\d-[0-3]\d[t\s](?:[0-2]\d:[0-5]\d:…d|23:59:60)(?:\.\d+)?(?:z|[+-]\d\d(?::?\d\d)?)$/i, uri: /^(?:[a-z][a-z0-9+\-.]*:)(?:\/?\/)?[^\s]*$/i, uri-reference: /^(?:(?:[a-z][a-z0-9+\-.]*:)?\/?\/)?(?:[^\\\s#][^\s#]*)?(?:#[^\\\s]*)?$/i, …}
_fragments: {}
_getId: ƒ _get$Id(schema)
_loadingSchemas: {}
_metaOpts: {$data: true, allErrors: true, loopRequired: Infinity, serialize: ƒ}
_opts:
$data: true
allErrors: true
loopRequired: Infinity
serialize: ƒ (data, opts)
__proto__: Object
_refs: {https://raw.githubusercontent.com/ajv-validator/ajv/master/lib/refs/data.json: SchemaObject, http://json-schema.org/draft-07/schema: SchemaObject, http://json-schema.org/schema: "http://json-schema.org/draft-07/schema"}
_schemas: {https://raw.githubusercontent.com/ajv-validator/ajv/master/lib/refs/data.json: SchemaObject, http://json-schema.org/draft-07/schema: SchemaObject}
__proto__: Object
```
Not sue if any of this helps find / fix the issue but I hope so!

**Comment by smeijer** [comment]
Ran into the same issue. Make sure to install v7. For some reason `npm i ajv` installed version 6, which threw the error.

Fixed with:

```
npm i ajv@7.1.0
```

**Comment by cywalker** [comment]
Thanks, got sorted via gitter post.
The issue was npm had installed v6 but npm v was reporting v7 that is inside ajv-formats package.
...which also explains some of the other unexpected behavior I was having prior to this fix.

**Comment by anonrig** [comment]
I'm having the same issue with Ajv 8 running on top of Fastify's latest version. Any fixes related to this?

**Comment by epoberezkin** [comment]
It has to be submitted to fastify too.

Maybe, the solution is to expose ajv instance in fastify and/or to pass options...

**Comment by anonrig** [comment]
I've sent a pull request to bump the dependencies, but it seems that the repo is unmaintained atm.

**Comment by vgjenks** [comment]
Same issue in latest AJV and formats - broken for me. Any hope in getting this fixed? We're basing a very large project on AJV and this really concerning. It breaks every time I update packages.

**Comment by epoberezkin** [comment]
I’m not 100% sure what is the right fix here.
It works correctly from clean install if I understood it correctly, but starts importing incorrect version after the update.

If that’s the case it’s more of annoying npm “feature” rather than the bug to be fixed in ajv…

I am open to ideas what’s the correct mitigation would be here.

**Comment by Prakash14one** [comment]
> Ran into the same issue. Make sure to install v7. For some reason `npm i ajv` installed version 6, which threw the error.
> 
> Fixed with:
> 
> ```
> npm i ajv@7.1.0
> ```

its working thanks

**Comment by lorenzogrv** [comment]
Same problem here, with ajv version 8.x

After some frustrated attemps, removing everything ajv-related and installing again worked. That is

```bash
npm rm -w our/tool ajv ajv-errors ajv-formats
npm install -w our/tool ajv ajv-errors ajv-formats
```

Hope it helps. Very strange :thinking:

**Comment by lorenzogrv** [comment]
After upgrading other non-related deps, got the same problem. My proposed workaround did not work. I suspect the problem arises from `ajv-formats` package having ajv within `dependencies`, when it should have it only within `peerDependencies`

**Comment by coderextreme** [comment]
Not really seeing a fix or workaround above?  I'm trying to migrate to ES6, ajv 8.12.0.  Only adding one parameter to addFormats.

import Ajv2020 from "../../../node_modules/ajv/dist/2020.js";
import addFormats from "../../../node_modules/ajv-formats/dist/index.js";
import localize from "../../../node_modules/ajv-i18n/localize/index.js";

const ajv = Ajv2020;
addFormats(ajv);
