### ISSUE TITLE
TypeScript error: Type 'FormatsPlugin' has no call signatures.

### ISSUE THREAD

**Issue by jpbecotte** [ajv-validator/ajv-formats#21]
Following the doc and simply trying to validate with the `date` format, I receive the following error: 

```
src/scripts/simple-validation.ts:5:1 - error TS2349: This expression is not callable.
  Type 'FormatsPlugin' has no call signatures.

5 addFormats(ajv);
  ~~~~~~~~~~
```

The source file is here:
```typescript
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const ajv = new Ajv();
addFormats(ajv);

const schema = {
  type: 'string',
  format: 'date',
};

const validate = ajv.compile(schema);
const isValid = validate('1-1-1');
console.log(isValid);
```

**Comment by epoberezkin** [comment]
potentially, installation problem? It can also be typescript version problem - FormatsPlugin extends Plugin, the latter has call signature, but FormatsPlugin does not redefine it.

**Comment by jbaramidze** [comment]
Same problem here

**Comment by epoberezkin** [comment]
What’s the typescript version? It is probably only going to work with 4+

**Comment by jbaramidze** [comment]
For me it's 4.1.5

**Comment by jbaramidze** [comment]
For me the problem was this:
https://stackoverflow.com/questions/66836206/npm-peer-dependency-of-depencency-is-missing-even-though-dependency-explicitly

Fixed by adding dependency on `ajv` to my service.

**Comment by jpbecotte** [comment]
I upgraded typescript and now it works! Thanks for pointing that out.

```
-    "typescript": "^4.1.3"
+    "typescript": "^4.2.3"
```
