### ISSUE TITLE
Documentation lists unsupported formats

### ISSUE THREAD

**Issue by lfrestrepog** [ajv-validator/ajv-formats#29]
Hello.

The readme lists the supported formats, including:
- byte: base64 encoded data
- int32: signed 32 bits integer
- int64: signed 64 bits integer
- float: float
- double: double
- password: password string
- binary: binary string

These are specified in [OpenAPI specification](https://spec.openapis.org/oas/v3.0.0#data-types), but not really supported by ajv-formats. Tested with version 2.0.2.

Thanks.

**Comment by lfrestrepog** [comment]
It appears the support for those formats is implemented, just not yet published in npm. Is there an estimated schedule for publication? Or maybe the details of pending work?

**Comment by epoberezkin** [comment]
Thanks for the ping!

**Comment by epoberezkin** [comment]
published 2.1.0
