### ISSUE TITLE
How to use with JTDSchema?

### ISSUE THREAD

**Issue by riker09** [ajv-validator/ajv-formats#34]
All examples I see use JSONSchema.

This is the shape I want to validate:

```typescript
interface MyData {
  name: string;
  email: string;
}
```

```typescript
import Ajv, { JTDDataType } from 'ajv/dist/jtd';
import addFormats from 'ajv-formats';

const ajv = new Ajv();
addFormats(ajv, ['email']);

const schema = {
  properties: {
    name: { type: 'string' },
    email: { type: 'string', format: 'email' }
  },
} as const;

const validate = ajv.compile<MyData>(schema);

const data: MyData = {
  name: 'John Doe',
  email: 'john.doe@example.com',
};

if (validate(data)) {
  // success!
}

```

However, i cannot get it to work. I'm using TypeScript v4.3.4.

The error I get is: 

```
Error: schema is invalid: data/properties must NOT have additional properties, data must have property 'ref', data must have property 'type', data must have property 'enum', data must have property 'elements', data/properties/email/type must NOT have additional properties, data/properties/email must have property 'ref', data/properties/email/type must be equal to one of the allowed values, data/properties/email must have property 'enum', data/properties/email must have property 'elements', data/properties/email must have property 'properties', data/properties/email must have property 'optionalProperties', data/properties/email must have property 'discriminator', data/properties/email must have property 'values', data/properties/email must match a schema in union, data/optionalProperties/age/type must NOT have additional properties, data/optionalProperties/age must have property 'ref', data/optionalProperties/age/type must be equal to one of the allowed values, data/optionalProperties/age must have property 'enum', data/optionalProperties/age must have property 'elements', data/optionalProperties/age must have property 'properties', data/optionalProperties/age must have property 'optionalProperties', data/optionalProperties/age must have property 'discriminator', data/optionalProperties/age must have property 'values', data/optionalProperties/age must match a schema in union, data must have property 'discriminator', data must have property 'values', data must match a schema in union
```

**Comment by epoberezkin** [comment]
"format" keyword is not defined in JTD.

You can register additional keywords from JSONSchema vocabulary and use them inside metadata member of the schema.

The examples on the site have toggles to switch to JTD.

**Comment by epoberezkin** [comment]
https://ajv.js.org/json-type-definition.html#user-defined-keywords

you would need to add format keyword definition from here: https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/format/format.ts (or better the same file compiled, in dist folder)

**Comment by riker09** [comment]
> "format" keyword is not defined in JTD.
> 
> You can register additional keywords from JSONSchema vocabulary and use them inside metadata member of the schema.
> 
> The examples on the site have toggles to switch to JTD.

After poking around with `ajv-formats` a little more I came to realize this. I would like to change my question: How can I have a property validate as `email` in JTD? A full working example would be nice. Sorry, I know that this is an issue tracker and my request is more a how do I...? type of thing. But I wasn't able to figure it out myself by reading the available documentation. Maybe I will change the title of this issue to "Provider better Getting Started documentation". 😄

**Comment by epoberezkin** [comment]
Something like this should work:

```typescript
import Ajv from "ajv/dist/jtd"
import ajvFormats from "ajv-formats"
import formatKeyword from "ajv/dist/vocabularies/format/format"

const ajv = new Ajv

ajv.addKeyword(format)
ajvFormats(ajv, "email")

const schema = {
  properties: {
    email: {
      type: "string"
      metadata: {format: "email"}
    }
  }
}
```

const validate = ajv.compile(schema)

const data = {
  email: "name@example.com"
}

console.log(validate(data))
```

**Comment by riker09** [comment]
Thanks for the fast reply. Yes, I was able to get it working with your example. There are two things to be aware of, however:

```typescript
import Ajv from "ajv/dist/jtd"
import ajvFormats from "ajv-formats"
import format from "ajv/dist/vocabularies/format/format" // Changed "formatKeyword" to "format"

const ajv = new Ajv

ajv.addKeyword(format)
ajvFormats(ajv, ["email"]) // This should be an array of strings

const schema = {
  properties: {
    email: {
      type: "string"
      metadata: {format: "email"}
    }
  }
}

const validate = ajv.compile(schema)

const data = {
  email: "name@example.com"
}

console.log(validate(data))
```

Maybe it is just me, but I was hoping a slightly simpler initial setup. That was not very intuitive, to say the least. But it is working now, so time for me to go out and write some schemas. Thank you very much for your lightning-fast responses.
