### ISSUE TITLE
idn-email is not supported when running 2020-12

### ISSUE THREAD

**Issue by hipitihop** [ajv-validator/ajv-formats#38]
`idn-email` is not supported.

**Environment:**
 schema: 2020-12
 node.JS: v12.18.2
 ajv: 8.6.2
 ajv-formats: 2.1.0

**Comment by epoberezkin** [comment]
as documented here: https://github.com/ajv-validator/ajv-formats#formats

**Comment by o5** [comment]
@epoberezkin Is there any reason why `idn-email` is not implemented directly in this library?
