### ISSUE TITLE
float and double are hardcoded to return true without validation

### ISSUE THREAD

**Issue by EyePulp** [ajv-validator/ajv-formats#39]
Howdy;
I'm assuming ignorance on my part, as I haven't dug into this far enough, but according to these lines: https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L79-L82 
```ts
  // C-type float
  float: {type: "number", validate: validateNumber},
  // C-type double
  double: {type: "number", validate: validateNumber},
```

Both `float` and `double` depend on the `validateNumber()` function which is here:  https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L206-L208

```ts
function validateNumber(): boolean {
  return true
}
```

Is this actually validating anything? Is something else responsible  for validation and this is just a pass-through of some sort?  Again I apologize if I'm missing something basic.

Thanks!

**Comment by epoberezkin** [comment]
These are just added to be defined for open-API specification, how would you validate float or double in JS, provided it's already a number?

**Comment by EyePulp** [comment]
@epoberezkin Thanks for the response.  It's confusing that `float` and `double` are listed in the documentation with no distinction alongside formats that **do** receive legitimate validation.
