### ISSUE TITLE
ES5 compatible export to dist required ("target": "es5")

### ISSUE THREAD

**Issue by teux** [ajv-validator/ajv-formats#4]
Hi,

There is object shorthand syntax in `node_modules/ajv-formats/dist/formats.js`.
```javascript
exports.fullFormats = {
    // date: http://tools.ietf.org/html/rfc3339#section-5.6
    date,
    // date-time: http://tools.ietf.org/html/rfc3339#section-5.6
    time,
```
Can you add `compilerOptions: { "target": "es5" }` in `tsconfig.json`, please?
Without this I can't use module in IE11.

I have also tried importing `node_modules/ajv-formats/src/index.ts`. 
But webpack 5 reports an error because of `module.exports` are used
```
module.exports = formatsPlugin
```

**Comment by epoberezkin** [comment]
Sorry, that would compile it to ES5 for all users... You need to recompile from source in your project.
