### ISSUE TITLE
Add semver

### ISSUE THREAD

**Issue by TimDaub** [ajv-validator/ajv-formats#58]
- https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
Would it make sense to add semver versioning formatting to this library? I could send a PR.

**Comment by epoberezkin** [comment]
Given that it’s probably just a regular expression it’s better to add in the application. Some non-standard format found its way here, I’d rather not grow the list… Sorry.

**Comment by TimDaub** [comment]
ok it's fine then I guess we can close this issue.
