### ISSUE TITLE
[FR] Allow empty string

### ISSUE THREAD

**Issue by rayfoss** [ajv-validator/ajv-formats#59]
# Summary

The following schema won't work:
```
createdAt: {
    type: 'string',
    format: 'iso-date-time',
    default: ''
}
```
as the default value will not pass validation if provided directly. 
Are there any plans to support empty strings as the null value? it tends to keep the Javascript engine optimized more often and reduces the need to do a fuzzy falsy check.

# Sandbox 
https://stackblitz.com/edit/vitejs-vite-ggyjmk?file=src/main.ts

# Workarounds
- Use pattern matching and make your own formats, ie: `/^()|([isodate])$/`
- Use the fact that undefined is not a valid JSON value to delete optional properties when needed, this seems tricky and implementation error prone, specially with patch calls and Datastore inconsistencies.
- Use the awful "0000-01-01T00:00:00.000Z" date.

**Comment by epoberezkin** [comment]
You could use anyOf with const: “” in the second branch.

I didn’t plan to support empty strings as null values, as they are not null values, sorry…

**Comment by rayfoss** [comment]
`formatEmptyable: true` would be nice for many folk. I updated my patch call code to delete data when it encounters undefined... this is what I'll do instead. I'm already using a heavily WebSockets reliant backend so RESTful HTTP issues are of no concern.

**Comment by APWHY** [comment]
A decent stopgap that worked for me was using the `reviver` argument in `JSON.parse` to 'clean' up all empty strings and replace them with `undefined`, thus removing them from the validator's eyes e.g. `const newData = JSON.parse(JSON.stringify(data), (_, v) =>v === '' ? undefined : v)`
