### ISSUE TITLE
Error: unknown format "iso-date-time"

### ISSUE THREAD

**Issue by modemmute** [ajv-validator/ajv-formats#64]
In testing, I've run across the following error - 

> Error: unknown format "iso-date-time" ignored in schema at path "#/properties/schema/properties/created"

I am using the following code:

```
const Ajv = require("ajv")
var addFormats = require("ajv-formats")

const ajv = new Ajv({allErrors: true})
addFormats(ajv, ["iso-date-time","uri"])

const schema = {
  type: "object",
  properties: {
    foo: {type: "string", "format": "uri"},
    bar: {type: "string", "format": "iso-date-time"}
  },
  additionalProperties: false,
}

const validate = ajv.compile(schema)

test({foo:"https://google.com",bar: "2022-06-11T00:11:59.000Z"})

function test(data) {
  const valid = validate(data)
  if (valid) console.log("Valid!")
  else console.log("Invalid: " + ajv.errorsText(validate.errors))
}
```
The `"format": "uri"` validates correctly, but the `"format": "iso-date-time"` throws an error. 

Any help appreciated!

**Comment by mikela** [comment]
You need to use https://github.com/ajv-validator/ajv-formats/releases/tag/v3.0.0-rc.0

**Comment by modemmute** [comment]
Thanks very much, appreciate the help.
