### ISSUE TITLE
openApi formats

### ISSUE THREAD

**Issue by seriousme** [ajv-validator/ajv-formats#9]
Hi,

Thanks for all the work on AJV !

I'm the author of [fastify-openapi-glue](https://github.com/seriousme/fastify-openapi-glue) and I have created [formats](https://github.com/seriousme/fastify-openapi-glue/blob/master/lib/oai-formats.js) for 
- int32
- int64
- float
- double 
- binary

as defined at https://swagger.io/docs/specification/data-models/data-types/

I presume that more AJV users will be using AJV for the parsing of openapi specs, would you be interested in a PR to add these formats to ajv-formats ?

Kind regards,
Hans

**Comment by epoberezkin** [comment]
Yes, particularly that ajv added discriminator support in v8, it makes sense to add these formats.

I'm about to release v2 of this package today, a shame I didn't spot it earlier, but it can be added to v2.1 if you can't add it now-ish :)

btw, binary and password that are no-op can be just defined as `true` (as opposed to `() => true`), the difference is that it would generate no validation code at all in case it is "true".

**Comment by epoberezkin** [comment]
I wasn't even watching this repo - that's why I missed...

**Comment by seriousme** [comment]
I can probably do add all formats in the next few hours.
Do you want to wait for #8 or should I do a PR myself ?

And a second question:
My current code relies on `decimal.js-light` but I noticed that `BigInt` is natively supported as of Node 10.4.0 so I'd prefer to use `BigInt` instead. Do you agree ?

Kind regards,
Hans
ps. I forgot about raising this issue too ;-)

**Comment by epoberezkin** [comment]
yes - please do it - you have it more-or-less done in the link :)

**Comment by seriousme** [comment]
Working on it, code is in place, now working on the tests ;-)

**Comment by epoberezkin** [comment]
> My current code relies on decimal.js-light but I noticed that BigInt is natively supported as of Node 10.4.0 so I'd prefer to use BigInt instead

I think it's already updated to use BigInt? Either way, even node 10 will end by May, so it's ok to use BigInt I think (it doesn't require that the number itself is BigInt, does it?)

**Comment by seriousme** [comment]
Just updated it to BigInt after my comment, also as an excercise for myself ;-)
BigInt also works with small numbers :-)

**Comment by seriousme** [comment]
Thx !
